### ISSUE TITLE
npm ERR! code ELIFECYCLE npm ERR! errno 1

### ISSUE THREAD

**Issue by clinto-abraham** [clinto92/ClintoResume#1]
npm start

> clintoresume@1.0.0 start C:\Users\Admin\Desktop\Full-Stack-Developer\CSS-Fancy CV\CSS Project 3\ClintoResume
> node index.js

file:///C:/Users/Admin/Desktop/Full-Stack-Developer/CSS-Fancy%20CV/CSS%20Project%203/ClintoResume/index.js:5
ReactDOM.render(<h1>Hello</h1>,document.getElementById('root'));
                ^

SyntaxError: Unexpected token '<'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)
    at async link (internal/modules/esm/module_job.js:47:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! clintoresume@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the clintoresume@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Roaming\npm-cache\_logs\2021-03-08T14_04_51_979Z-debug.log

[2021-03-08T13_28_00_847Z-debug.log](https://github.com/clinto92/ClintoResume/files/6101873/2021-03-08T13_28_00_847Z-debug.log)

**Comment by clinto-abraham** [comment]
npm updated along with node.js, later created new react.js app using :
After this ELIFECYCLE npm ERR! errno1 went away.
npm init react-app my-app
: After this step whole error passed away.  Ingested GitHub file by git clone 'the_link_from_https' inside the hyper terminal
